server:
  port: 8402

spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


payment:
  toss:
    secret-key: ${TOSS_SECRET_KEY:test_sk_여기에실제키입력}
    client-key: ${TOSS_CLIENT_KEY:test_ck_여기에실제키입력}
    base-url: https://api.tosspayments.com/v1
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY:여기에실제키입력}
    base-url: https://kapi.kakao.com/v1/payment

jwt:
  secret: ikea2026SpringBootJwtSecretKeySecureABC

app:
  cors:
    allowed-origins: http://localhost:5173

file:
  upload-dir: C:/uploads/products/

logging:
  level:
    org.springframework.security: DEBUG