spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/ikea
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 여기에_로컬_시크릿 sdfsdfsdfawebsdfbdbzdfbrdf

payment:
  toss:
    secret-key: test_sk_QbgMGZzorzb5y6a5QN9Krl5E1em4
    client-key: test_ck_26DlbXAaV0Lv5Gn6jPqnVqY50Q9R
  kakao:
    secret-key: DEV974EEEDEFDAB1AB260371A06EB8D910F2E279