-- =========================================================
-- IKEA 쇼핑몰 백엔드 (PostgreSQL) 초기 실행용 DDL
-- =========================================================

CREATE TABLE category (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE members (
    member_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id        VARCHAR(50)  NOT NULL UNIQUE,
    password        VARCHAR(100) NOT NULL,
    name            VARCHAR(50)  NOT NULL,
    email           VARCHAR(254) NOT NULL UNIQUE,
    phone_number    VARCHAR(255) NOT NULL UNIQUE,
    zone_code       VARCHAR(10),
    address_main    VARCHAR(255),
    address_detail  VARCHAR(255),
    created_at      TIMESTAMP,
    member_role     VARCHAR(20)
                   CHECK (member_role IN ('USER', 'ADMIN')),
    deleted         BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE products (
    product_id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    price                 INTEGER NOT NULL,
    original_price        INTEGER,
    img_path              TEXT NOT NULL,
    brand                 VARCHAR(100),
    badge                 VARCHAR(100),
    label                 VARCHAR(100),
    type_slug             VARCHAR(100),
    attributes            TEXT,
    detail_content        TEXT,
    gallery_images        TEXT,
    dimension_image_path  VARCHAR(500),
    created_at            TIMESTAMP,
    category_id           BIGINT,
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES category(id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE TABLE product_stocks (
    stock_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL UNIQUE,
    quantity      INTEGER NOT NULL,
    updated_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_product_stocks_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE carts (
    cart_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT UNIQUE,
    guest_cart_key  VARCHAR(100) UNIQUE,
    CONSTRAINT fk_carts_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE TABLE cart_items (
    cart_item_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id        BIGINT NOT NULL,
    product_id     BIGINT NOT NULL,
    quantity       INTEGER NOT NULL,
    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id) REFERENCES carts(cart_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE notices (
    notice_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(200) NOT NULL,
    content       TEXT NOT NULL,
    writer        VARCHAR(50) NOT NULL,
    view_count    INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMP NOT NULL,
    updated_at    TIMESTAMP NOT NULL
);

CREATE TABLE notice_attachments (
    notice_attachment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id             BIGINT NOT NULL,
    original_name         VARCHAR(255) NOT NULL,
    stored_name           VARCHAR(255),
    file_url              VARCHAR(255),
    content_type          VARCHAR(120),
    file_size             BIGINT NOT NULL,
    file_data             BYTEA,
    CONSTRAINT fk_notice_attachments_notice
        FOREIGN KEY (notice_id) REFERENCES notices(notice_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TABLE qnas (
    qna_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level          INTEGER NOT NULL,
    parent_id      BIGINT,
    title          VARCHAR(100) NOT NULL,
    content        TEXT NOT NULL,
    writer         VARCHAR(255) NOT NULL,
    member_id      BIGINT,
    phone_number   VARCHAR(255),
    email          VARCHAR(255),
    view_count     INTEGER NOT NULL DEFAULT 0,
    created_at     TIMESTAMP NOT NULL
);

CREATE TABLE orders (
    order_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no       VARCHAR(50) NOT NULL UNIQUE,
    member_id      BIGINT,
    order_status   VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                  CHECK (order_status IN ('PENDING', 'PAID', 'ORDERED', 'CANCELLED', 'DELIVERING', 'COMPLETED')),
    total_price    INTEGER NOT NULL,
    final_price    INTEGER NOT NULL,
    address        VARCHAR(254) NOT NULL,
    guest_name     VARCHAR(50),
    guest_phone    VARCHAR(20),
    CONSTRAINT fk_orders_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE TABLE order_items (
    order_item_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        BIGINT NOT NULL,
    product_id      BIGINT NOT NULL,
    quantity        INTEGER NOT NULL,
    order_price     INTEGER NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE payments (
    payment_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT NOT NULL UNIQUE,
    member_id        BIGINT,
    payment_method   VARCHAR(20) NOT NULL
                    CHECK (payment_method IN ('TOSS', 'KAKAO', 'BANK_TRANSFER')),
    method_no        VARCHAR(100),
    transaction_id   VARCHAR(100),
    amount           INTEGER NOT NULL,
    payment_status   VARCHAR(20) NOT NULL DEFAULT 'PENDING'
                    CHECK (payment_status IN ('PENDING', 'OK', 'CANCEL', 'FAILED')),
    response_data    TEXT,
    cancel_reason    VARCHAR(255),
    created_at       TIMESTAMP NOT NULL,
    paid_at          TIMESTAMP,
    cancelled_at     TIMESTAMP,
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_payments_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE TABLE reviews (
    review_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT,
    order_id       BIGINT,
    product_id     BIGINT,
    content        TEXT NOT NULL,
    rating         INTEGER NOT NULL,
    created_at     TIMESTAMP NOT NULL,
    CONSTRAINT fk_reviews_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_reviews_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE TABLE refresh_tokens (
    refresh_token_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id           VARCHAR(255) NOT NULL UNIQUE,
    refresh_token      VARCHAR(255) NOT NULL,
    member_role        VARCHAR(255) NOT NULL
);

CREATE INDEX idx_products_category_id            ON products(category_id);

CREATE INDEX idx_carts_member_id                 ON carts(member_id);
CREATE INDEX idx_cart_items_cart_id              ON cart_items(cart_id);
CREATE INDEX idx_cart_items_product_id           ON cart_items(product_id);

CREATE INDEX idx_notice_attachments_notice_id    ON notice_attachments(notice_id);

CREATE INDEX idx_qnas_member_id                  ON qnas(member_id);
CREATE INDEX idx_qnas_parent_id                  ON qnas(parent_id);

CREATE INDEX idx_orders_member_id                ON orders(member_id);
CREATE INDEX idx_orders_order_status             ON orders(order_status);

CREATE INDEX idx_order_items_order_id            ON order_items(order_id);
CREATE INDEX idx_order_items_product_id          ON order_items(product_id);

CREATE INDEX idx_payments_member_id              ON payments(member_id);
CREATE INDEX idx_payments_transaction_id         ON payments(transaction_id);

CREATE INDEX idx_reviews_member_id               ON reviews(member_id);
CREATE INDEX idx_reviews_order_id                ON reviews(order_id);
CREATE INDEX idx_reviews_product_id              ON reviews(product_id);
