-- =========================================================
-- IKEA 쇼핑몰 백엔드 최종 DDL (PostgreSQL)
-- 기준: src/main/java/com/example/ikea/domain/*.java
-- 용도: 빈 DB(초기화 상태)에 바로 실행하는 최종 스키마
-- 작성일: 2026-04-10
-- =========================================================

-- 실행 편의를 위해 트랜잭션으로 감쌉니다.
BEGIN;

-- =========================================================
-- 1. TABLES
-- =========================================================

CREATE TABLE category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE members (
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    phone_number VARCHAR(255) NOT NULL UNIQUE,
    zone_code VARCHAR(10),
    address_main VARCHAR(255),
    address_detail VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    member_role VARCHAR(20) NOT NULL DEFAULT 'USER',
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT chk_members_role
        CHECK (member_role IN ('USER', 'ADMIN'))
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(100) UNIQUE,
    name VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    original_price INTEGER,
    img_path TEXT NOT NULL,
    brand VARCHAR(100),
    badge VARCHAR(100),
    label VARCHAR(100),
    type_slug VARCHAR(100),
    attributes TEXT,
    detail_content TEXT,
    gallery_images TEXT,
    dimension_image_path VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_id BIGINT,
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES category(id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_products_price
        CHECK (price >= 0),
    CONSTRAINT chk_products_original_price
        CHECK (original_price IS NULL OR original_price >= 0)
);

CREATE TABLE product_stocks (
    stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL UNIQUE,
    quantity INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_stocks_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT chk_product_stocks_quantity
        CHECK (quantity >= 0)
);

CREATE TABLE carts (
    cart_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT UNIQUE,
    guest_cart_key VARCHAR(100) UNIQUE,
    CONSTRAINT fk_carts_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_carts_owner
        CHECK (
            (member_id IS NOT NULL AND guest_cart_key IS NULL)
            OR
            (member_id IS NULL AND guest_cart_key IS NOT NULL)
        )
);

CREATE TABLE cart_items (
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT fk_cart_items_cart
        FOREIGN KEY (cart_id) REFERENCES carts(cart_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_cart_items_cart_product
        UNIQUE (cart_id, product_id),
    CONSTRAINT chk_cart_items_quantity
        CHECK (quantity > 0)
);

CREATE TABLE notices (
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    writer VARCHAR(50) NOT NULL,
    view_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_notices_view_count
        CHECK (view_count >= 0)
);

CREATE TABLE notice_attachments (
    notice_attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id BIGINT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255),
    file_url VARCHAR(255),
    content_type VARCHAR(120),
    file_size BIGINT NOT NULL,
    file_data BYTEA,
    CONSTRAINT fk_notice_attachments_notice
        FOREIGN KEY (notice_id) REFERENCES notices(notice_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT chk_notice_attachments_file_size
        CHECK (file_size >= 0)
);

CREATE TABLE qnas (
    qna_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level INTEGER NOT NULL,
    parent_id BIGINT,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    writer VARCHAR(255) NOT NULL,
    member_id BIGINT,
    phone_number VARCHAR(255),
    email VARCHAR(255),
    view_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_qnas_level
        CHECK (level >= 0),
    CONSTRAINT chk_qnas_view_count
        CHECK (view_count >= 0),
    CONSTRAINT fk_qnas_parent
        FOREIGN KEY (parent_id) REFERENCES qnas(qna_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_qnas_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(50) NOT NULL UNIQUE,
    member_id BIGINT,
    order_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    total_price INTEGER NOT NULL,
    final_price INTEGER NOT NULL,
    address VARCHAR(254) NOT NULL,
    guest_name VARCHAR(50),
    guest_phone VARCHAR(20),
    CONSTRAINT fk_orders_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_orders_status
        CHECK (order_status IN ('PENDING', 'PAID', 'ORDERED', 'CANCELLED', 'DELIVERING', 'COMPLETED')),
    CONSTRAINT chk_orders_total_price
        CHECK (total_price >= 0),
    CONSTRAINT chk_orders_final_price
        CHECK (final_price >= 0),
    CONSTRAINT chk_orders_owner
        CHECK (
            (member_id IS NOT NULL AND guest_name IS NULL AND guest_phone IS NULL)
            OR
            (member_id IS NULL AND guest_name IS NOT NULL AND guest_phone IS NOT NULL)
        )
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    order_price INTEGER NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_order_items_quantity
        CHECK (quantity > 0),
    CONSTRAINT chk_order_items_price
        CHECK (order_price >= 0)
);

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    member_id BIGINT,
    payment_method VARCHAR(20) NOT NULL,
    method_no VARCHAR(100),
    transaction_id VARCHAR(100),
    amount INTEGER NOT NULL,
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    response_data TEXT,
    cancel_reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    CONSTRAINT fk_payments_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('TOSS', 'KAKAO', 'BANK_TRANSFER')),
    CONSTRAINT chk_payments_status
        CHECK (payment_status IN ('PENDING', 'OK', 'CANCEL', 'FAILED')),
    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0)
);

CREATE TABLE reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT,
    order_id BIGINT,
    product_id BIGINT,
    content TEXT NOT NULL,
    rating INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_member
        FOREIGN KEY (member_id) REFERENCES members(member_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_reviews_order
        FOREIGN KEY (order_id) REFERENCES orders(order_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id) REFERENCES products(product_id)
        ON UPDATE RESTRICT ON DELETE SET NULL,
    CONSTRAINT chk_reviews_rating
        CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(255) NOT NULL UNIQUE,
    refresh_token VARCHAR(255) NOT NULL,
    member_role VARCHAR(255) NOT NULL,
    CONSTRAINT chk_refresh_tokens_role
        CHECK (member_role IN ('USER', 'ADMIN'))
);

-- =========================================================
-- 2. INDEXES
-- =========================================================

CREATE INDEX idx_products_category_id ON products(category_id);
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_brand ON products(brand);
CREATE INDEX idx_products_type_slug ON products(type_slug);

CREATE INDEX idx_carts_member_id ON carts(member_id);
CREATE INDEX idx_cart_items_cart_id ON cart_items(cart_id);
CREATE INDEX idx_cart_items_product_id ON cart_items(product_id);

CREATE INDEX idx_notice_attachments_notice_id ON notice_attachments(notice_id);

CREATE INDEX idx_qnas_member_id ON qnas(member_id);
CREATE INDEX idx_qnas_parent_id ON qnas(parent_id);
CREATE INDEX idx_qnas_created_at ON qnas(created_at DESC);

CREATE INDEX idx_orders_member_id ON orders(member_id);
CREATE INDEX idx_orders_order_status ON orders(order_status);
CREATE INDEX idx_orders_guest_phone ON orders(guest_phone);

CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);

CREATE INDEX idx_payments_member_id ON payments(member_id);
CREATE INDEX idx_payments_order_id ON payments(order_id);
CREATE INDEX idx_payments_payment_status ON payments(payment_status);
CREATE INDEX idx_payments_created_at ON payments(created_at DESC);
CREATE UNIQUE INDEX uq_payments_transaction_id_not_null
    ON payments(transaction_id)
    WHERE transaction_id IS NOT NULL;

CREATE INDEX idx_reviews_member_id ON reviews(member_id);
CREATE INDEX idx_reviews_order_id ON reviews(order_id);
CREATE INDEX idx_reviews_product_id ON reviews(product_id);
CREATE INDEX idx_reviews_created_at ON reviews(created_at DESC);

-- =========================================================
-- 3. OPTIONAL COMMENTS
-- =========================================================

COMMENT ON TABLE category IS '상품 카테고리';
COMMENT ON TABLE members IS '회원';
COMMENT ON TABLE products IS '상품';
COMMENT ON TABLE product_stocks IS '상품 재고';
COMMENT ON TABLE carts IS '장바구니(회원 또는 비회원)';
COMMENT ON TABLE cart_items IS '장바구니 상품';
COMMENT ON TABLE notices IS '공지사항';
COMMENT ON TABLE notice_attachments IS '공지사항 첨부파일';
COMMENT ON TABLE qnas IS '문의 게시판';
COMMENT ON TABLE orders IS '주문';
COMMENT ON TABLE order_items IS '주문 상품';
COMMENT ON TABLE payments IS '결제';
COMMENT ON TABLE reviews IS '리뷰';
COMMENT ON TABLE refresh_tokens IS 'JWT 리프레시 토큰';

COMMIT;
